# Generated by Django 5.1.7 on 2026-02-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('house_no_or_street', models.CharField(max_length=500)),
                ('landmark', models.CharField(blank=True, max_length=500, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
