# Generated by Django 5.1.7 on 2026-02-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.identity'),
        ),
    ]
