# Generated by Django 5.1.7 on 2026-02-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_our_users_options_alter_our_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='our_users',
            options={},
        ),
        migrations.AlterModelManagers(
            name='our_users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='our_users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='our_users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='our_users',
            name='last_name',
        ),
    ]
