# Generated by Django 5.1.7 on 2026-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='Watch', max_length=1000),
            preserve_default=False,
        ),
    ]
